id: P004393
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:17:51.557993
source_metadata:
  id: bdr:W27606
  title: གུ་རུའི་ཚིག་བདུན་གསོལ་འདེབས་ཀྱི་རྣམ་བཤད་རྡོ་རྗེའི་ཚིག་གི་མདུད་གྲོལ
  author: ''
  volumes:
    bba7f1c8d6b04199a176720018b91848:
      image_group_id: I4512
      title: ''
      volume_number: 1
      total_pages: 30
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
